name: google_apps
description: Libraries to allow writing Google Apps Scripts.
version: 0.0.1
author: Florian Loitsch <florian@loitsch.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
